// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAICxH5c0SIhU8TvxWDnOsLWVop9Q0CVcg',
    appId: '1:444432984710:web:3cfe855bbee4e522d43f07',
    messagingSenderId: '444432984710',
    projectId: 'estrella-sanriocharacter-d7b38',
    authDomain: 'estrella-sanriocharacter-d7b38.firebaseapp.com',
    databaseURL: 'https://estrella-sanriocharacter-d7b38-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'estrella-sanriocharacter-d7b38.firebasestorage.app',
    measurementId: 'G-JGEGXFCTZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3YBSu2BQWEopqo3QgDL07LiaDHaeeqKs',
    appId: '1:444432984710:android:454c6e02d78a23e3d43f07',
    messagingSenderId: '444432984710',
    projectId: 'estrella-sanriocharacter-d7b38',
    databaseURL: 'https://estrella-sanriocharacter-d7b38-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'estrella-sanriocharacter-d7b38.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAICxH5c0SIhU8TvxWDnOsLWVop9Q0CVcg',
    appId: '1:444432984710:web:47ed789dba1de654d43f07',
    messagingSenderId: '444432984710',
    projectId: 'estrella-sanriocharacter-d7b38',
    authDomain: 'estrella-sanriocharacter-d7b38.firebaseapp.com',
    databaseURL: 'https://estrella-sanriocharacter-d7b38-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'estrella-sanriocharacter-d7b38.firebasestorage.app',
    measurementId: 'G-H9DK5GTNM6',
  );
}
